# Generated by Django 5.0.7 on 2024-12-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_studentcourse_evaluation_submitted_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentcourse",
            name="create_time",
        ),
        migrations.AlterField(
            model_name="studentcourse",
            name="assessment",
            field=models.TextField(null=True, verbose_name="评价内容"),
        ),
        migrations.AlterField(
            model_name="studentcourse",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (5, "优秀 (5分)"),
                    (4, "良好 (4分)"),
                    (3, "一般 (3分)"),
                    (2, "较差 (2分)"),
                    (1, "差 (1分)"),
                ],
                null=True,
                verbose_name="评分",
            ),
        ),
        migrations.AlterField(
            model_name="studentcourse",
            name="with_draw_time",
            field=models.DateTimeField(null=True),
        ),
    ]
