# Generated by Django 5.0.7 on 2024-12-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_remove_studentcourse_create_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcourse",
            name="is_anonymous",
            field=models.BooleanField(default=True, verbose_name="是否匿名"),
        ),
    ]
